<div class="block">
                <h2 class="blockhead">Gerenciar Personagem</h2>
                <div class="blockbody">
                        <ul class="blockrow">
				<li class="inactive"><a href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=MANAGE_CHAR','Panel_Nav','GET');">Gerenciando: {Manage_Char}</a></li>
				<li class="inactive"><a rel="panel" title="{Char_Reset#1},{Char_Reset#2},{Char_Reset#3}" str="Resetar Personagem" href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=RESET_CHAR','Panel_Nav','GET');">Resetar Personagem</a></li>
				<li class="inactive"><a rel="panel" title="{Char_MReset#1},{Char_MReset#2},{Char_MReset#3}" str="Master Reset" href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=MASTER_RESET','Panel_Nav','GET');">Master Reset</a></li>
                <li class="inactive"><a rel="panel" title="{Char_TReset#1},{Char_TReset#2},{Char_TReset#3}" str="Transferir Resets" href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=TRANSFER_RESETS','Panel_Nav','GET');">Transferir Resets</a></li>
                <li class="inactive"><a rel="panel" title="{Char_TRCash#1},{Char_TRCash#2},{Char_TRCash#3}" str="Trocar Resets por {%TRADE_RCOIN%}" href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=TRADE_RCASH','Panel_Nav','GET');">Trocar Resets por {%TRADE_RCOIN%}</a></li>
				<li class="inactive"><a rel="panel" title="{Char_Clear_PK#1},{Char_Clear_PK#2},{Char_Clear_PK#3}" str="Limpar PK/Hero" href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=CLEAR_PK','Panel_Nav','GET');">Limpar PK/Hero</a></li>
				<li class="inactive"><a rel="panel" title="{Char_Change_Class#1},{Char_Change_Class#2},{Char_Change_Class#3}" str="Alterar Classe" href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=CHANGE_CLASS','Panel_Nav','GET');">Alterar Classe</a></li>
				<li class="inactive"><a rel="panel" title="{Char_Change_Nick#1},{Char_Change_Nick#2},{Char_Change_Nick#3}" str="Alterar Nick" href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=CHANGE_NICK','Panel_Nav','GET');">Alterar Nick</a></li>
				<li class="inactive"><a rel="panel" title="{Char_Move_Char#1},{Char_Move_Char#2},{Char_Move_Char#3}" str="Mover Personagem" href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=MOVE_CHAR','Panel_Nav','GET');">Mover Personagem</a></li>
				<li class="inactive"><a rel="panel" title="{Char_Profile_Char#1},{Char_Profile_Char#2},{Char_Profile_Char#3}" str="Gerenciar Perfil" href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=PROFILE_CHAR','Panel_Nav','GET');">Gerenciar Perfil</a></li>
				<li class="inactive"><a rel="panel" title="{Char_Upload_Img#1},{Char_Upload_Img#2},{Char_Upload_Img#3}" str="Gerenciar Imagem" href="javascript: void(EffectWeb);" onclick="window.open('?pag=paneluser&str=UPLOAD_IMG', 'Gerenciar Imagem', 'width=430, height=240, top=50, left=50, scrollbars=no, status=no, toolbar=no, location=no, directories=no, menubar=no, resizable=no, fullscreen=no');">Gerenciar Imagem</a></li>
                <li class="inactive"><a rel="panel" title="{Char_Concert_Points#1},{Char_Concert_Points#2},{Char_Concert_Points#3}" str="Concertar Pontos" href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=CONCERT_POINTS','Panel_Nav','GET');">Concertar Pontos</a></li>
				<li class="inactive"><a rel="panel" title="{Char_Reset_Points#1},{Char_Reset_Points#2},{Char_Reset_Points#3}" str="Resetar Pontos" href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=RESET_POINTS','Panel_Nav','GET');">Resetar Pontos</a></li>
				<li class="inactive"><a rel="panel" title="{Char_Distribute_Points#1},{Char_Distribute_Points#2},{Char_Distribute_Points#3}" str="Distribuir Pontos" href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=DISTRIBUTE_POINTS','Panel_Nav','GET');">Distribuir Pontos</a></li>
				<li class="inactive"><a rel="panel" title="{Char_Clear_Char#1},{Char_Clear_Char#2},{Char_Clear_Char#3}" str="Limpar Personagem" href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=CLEAR_CHAR','Panel_Nav','GET');">Limpar Personagem</a></li>
				<li class="inactive"><a href="javascript: void(EffectWeb);" onclick="CTM_Load('?pag=paneluser&str=CLOSE_CHAR','Panel_Nav','GET');">Fechar Gerenciamento</a></li>
                        </ul>
                </div>
        </div>